"""
examples/train_demo_model.py — generates a complete, ready-to-run
Whitebox demo in under 10 seconds, with no external data download and
no domain-specific setup. This exists so a brand-new user can verify
the whole pipeline works BEFORE wiring up their own real model.

What it produces (in examples/demo/):
    demo_model.pkl    — a trained RandomForestClassifier
    demo_data.csv      — the feature matrix + a 'target' column
    demo_adapter.py    — a ready-to-use adapter pointing at demo_model.pkl

Run it, then immediately try:
    python examples/train_demo_model.py
    cd examples/demo
    whitebox audit --data demo_data.csv --target target --adapter demo_adapter.py
"""

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

OUT_DIR = Path(__file__).parent / "demo"


def main():
    OUT_DIR.mkdir(exist_ok=True)

    data = load_breast_cancer()
    X, y = data.data, data.target
    feature_names = list(data.feature_names)

    # Standardize — Whitebox's adversarial audit assumes standardized
    # feature space (see attacks.py's decoy_alpha docstring), the
    # same way the original NIDS prototype standardized its inputs.
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    X_train, X_test, y_train, y_test = train_test_split(
        X_scaled, y, test_size=0.2, random_state=42, stratify=y
    )

    model = RandomForestClassifier(n_estimators=100, max_depth=8, random_state=42)
    model.fit(X_train, y_train)
    test_acc = model.score(X_test, y_test)
    print(f"Demo model trained. Test accuracy: {test_acc:.4f}")

    joblib.dump(model, OUT_DIR / "demo_model.pkl")

    df = pd.DataFrame(X_scaled, columns=feature_names)
    df["target"] = y
    df.to_csv(OUT_DIR / "demo_data.csv", index=False)

    adapter_code = f'''"""
Auto-generated by examples/train_demo_model.py — a ready-to-run
adapter for the demo RandomForestClassifier trained on sklearn's
breast cancer dataset (binary classification, 30 numeric features).
"""

import joblib
import numpy as np
from pathlib import Path

_model = joblib.load(Path(__file__).parent / "demo_model.pkl")

FEATURE_NAMES = {feature_names!r}


def predict_proba(X: np.ndarray) -> np.ndarray:
    return _model.predict_proba(X)[:, 1]
'''
    (OUT_DIR / "demo_adapter.py").write_text(adapter_code, encoding="utf-8")

    print(f"\nDemo files written to {OUT_DIR}/")
    print("\nTry it now:")
    print(f"  cd {OUT_DIR}")
    print("  whitebox audit --data demo_data.csv --target target --adapter demo_adapter.py")


if __name__ == "__main__":
    main()
